Make examples usable with Python 3
psss/python-nitrate pull request #27
Opened 2021-03-02 15:38 UTC by stepnem

That seems to have been the intention, as the shebang already assumes
python3.

I haven't tried actually running create.py (it looks more like just
a collection of examples), but matrix.py now does work as a python3
script.

Fixes: 90b1d68227df ("Migrate the code to Python 3")

2021-04-01 17:09 UTC, ZelenyMartin commented on examples/matrix.py
> +                    print(caserun.status.shortname)
Trailing comma of python2's `print` command should be converted to `end=' '` parameter of python3's `print()` function.

Example:
```
$ cat test_python2.py 
#!/usr/bin/python2
print "a",
print "b"

$ ./test_python2.py 
a b


$ cat test_python3.py 
#!/usr/bin/python3
print("a", end=' ')
print("b")

$ ./test_python3.py 
a b
```

2to3 says so:
```
$ 2to3 test_python3.py -w
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored test_python3.py
--- test_python3.py	(original)
+++ test_python3.py	(refactored)
@@ -1,4 +1,4 @@
 #!/usr/bin/python3
 
-print "a",
-print "b"
+print("a", end=' ')
+print("b")
RefactoringTool: Files that were modified:
RefactoringTool: test_python3.py
```

2021-04-01 17:12 UTC, ZelenyMartin requested changes
python2's trailing comma is not converted exactly the same

2021-04-01 17:12 UTC, ZelenyMartin commented on examples/matrix.py
> +                print("....")
Same here

2021-04-06 15:28 UTC, stepnem commented
> Trailing comma of python2's print command should be converted to end='  ' parameter of python3's print() function.

Fixed, sorry for the oversight.

2021-04-07 07:46 UTC, ZelenyMartin approved these changes

2021-04-07 07:47 UTC, merged